[versions]
neo = { strictly = "[20.4.198,20.5)", prefer = "latest.release" }
jei = { strictly = "[17.3,18.0)", prefer = "latest.release" }
api = { strictly = "[1,2)", prefer = "latest.release" }
neogradle = { strictly = "[7,8)", prefer = "latest.release" }
minotaur = { strictly = "[2,3)", prefer = "latest.release" }

[libraries]
neo = { group = "net.neoforged", name = "neoforge", version.ref = "neo" }
jei = { group = "mezz.jei", name = "jei-1.20.4-neoforge", version.ref = "jei" }
api = { group = "io.github.zygzaggaming.hearty.api", name = "hearty-1.20.4-neoforge-api", version.ref = "api" }

[bundles]

[plugins]
ng-userdev = { id = "net.neoforged.gradle.userdev", version.ref = "neogradle" }
ng-mixin = { id = "net.neoforged.gradle.mixin", version.ref = "neogradle" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
